---
  - hosts: web
    become: yes

    roles:
      - web

  - hosts: harvester
    become: yes
    
    roles:
      - harvester
  
  - hosts: analyser
    become: yes
    
    roles:
      - analyser