---
# tasks file for analyser

- name: Install Python3
  become: yes
  apt:
   name: python3
   state: present

- name: Install Python3 Pip
  become: yes
  apt:
   name: python3-pip
   state: present

- name: Install Pip
  become: yes
  apt:
   name: python-pip
   state: present

- name: Install Python3 NLTK
  become: yes
  apt:
   name: python3-nltk
   state: present

- name: Install Numpy
  become: yes
  apt:
   name: python-numpy
   state: present

- name: Install NLTK
  become: yes
  pip:
   name: nltk

- name: Install sklearn
  become: yes
  pip: 
   name: sklearn

- name: Install scipy
  become: yes
  pip: 
   name: scipy

- name: Install pandas
  become: yes
  pip: 
   name: pandas

- name: Initialise!
  command: python3 init.py
  args:
    chdir: "{{homeDir}}/{{appDir}}/sentimentanalysis"


- name: Start the analyser!
  shell: python sentimentanalysis.py input/ output/  >sentiment.log 2>sentiment.err &
  async: 10
  poll: 0
  args:
    chdir: "{{homeDir}}/{{appDir}}/sentimentanalysis"