---
- hosts: all
  sudo: yes
  gather_facts: yes

  vars:
    - homeDir: /home/ubuntu
    - appDir : twitter_analytics
    - repoName : twitter-analytics
    - githubAccount: mpanneer

  tasks:
    - name: Install the package "git"
      apt:
        name: git
        state: present

    - name: Install "pm2" node.js package.
      npm: name=pm2 global=yes production=yes

    - name: Install "http-server" node.js package.
      npm: name=http-server global=yes

    - name: Create a directory for the App
      file: path={{homeDir}}/{{appDir}} state=directory

    - name: Clone the Git repo
      git: repo=https://github.com/{{githubAccount}}/{{repoName}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes
      register: git_finished

    - name: Running NPM install on the UI app
      npm: path={{homeDir}}/{{appDir}}/API
      register: npm_finished
      when: git_finished.changed

    - name: Start APP
      sudo_user: ubuntu
      command: pm2 start server.js --name app chdir={{homeDir}}/{{appDir}}/API
      ignore_errors: yes
      when: npm_finished.changed