HeatTemplateFormatVersion: '2012-12-12'

Description: >
  Template to creat the Web instance.
Parameters:
  ImageId:
    Type: String
    Description:
      Image Id.
  KeyName:
    Type: String
    Description:
      Name of an existing key pair to enable SSH access to the instance.
  InstanceType:
    Type: String
    Description: Type of the instance to be created.
    Default: m1.small
    AllowedValues: [m1.small, m1.medium, m1.large, m1.xlarge, m1.xxlarge]
  AvailabilityZone:
    Type: String
    Description: The NeCTAR zone in which the VM is to run (must have block storage)
    Default: melbourne-np
    AllowedValues: [melbourne-qh2, melbourne-np, monash, qld]

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable ssh access and icmp"
      SecurityGroupEgress:
        -
          CidrIp: "0.0.0.0/0"
        -
          CidrIp: "::/0"
      SecurityGroupIngress:
        -
          IpProtocol: "icmp"
          FromPort: "-1"
          ToPort: "-1"
          CidrIp: "0.0.0.0/0"
        -
          IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        -
          IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0" 
        -
          IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0" 
        -
          IpProtocol: "tcp"
          FromPort: "8000"
          ToPort: "8000"
          CidrIp: "0.0.0.0/0"  
  NovaInstance:
    Type: OS::Nova::Server
    Properties:
      availability_zone: { Ref: AvailabilityZone }
      image: { Ref: ImageId }
      flavor: { Ref: InstanceType }
      key_name: { Ref: KeyName }
      security_groups:
        - { Ref: SecurityGroup }
      user_data:

Outputs:
  InstanceIP:
    Description: Public IP address of the newly created instance.
    Value:
      Fn::GetAtt:
      - NovaInstance
      - first_address
