---
# tasks file for harvester

- name: Install java
  become: yes
  apt:
   name: openjdk-8-jre-headless
   state: present

- name: Clone the Git repo
  git: repo=https://github.com/{{githubAccount}}/{{repoName}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes
  register: git_finished

- name: Create a properties file
  template: 
    src: templates/configTweetSearchFileMel1.properties
    dest: "{{homeDir}}/{{appDir}}/harvester/config/configTweetSearchFileMel1.properties"

- name: Creates logs directory
  file: path="{{homeDir}}/{{appDir}}/harvester/logs" state=directory

- name: Creates working directory
  file: path="{{homeDir}}/{{appDir}}/harvester/working" state=directory

- name: Creates input directory
  file: path="{{homeDir}}/{{appDir}}/analyser/input" state=directory

- name: Creates output directory
  file: path="{{homeDir}}/{{appDir}}/analyser/output" state=directory

- file:
    path: "{{homeDir}}/{{appDir}}/harvester/startup.sh"
    state: touch
    mode: "+x"
 
- name: Start the harvesters
  command: sh startup.sh
  args:
    chdir: /home/ubuntu/twitter_analytics/harvester